POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbGFtYWhhcnJpIiwiaWQiOiI1YThlMWYxOWNmZjE3YzJiOTBkMjBkYzYiLCJpYXQiOjE1MTkyNjM5MjB9.WqckNhbvIGR57MH2Bgt-nOhFGyj_m1TodmD9TTSiM_8

{
    "title": "Kuinka voittaa taistelu väsymstä vastaan",
    "author": "Salama Härri Itse",
    "url": "http://ahah4h4.blogspot.com"
}